# Generated by Django 3.2.5 on 2021-07-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=200)),
                ('title_eng', models.CharField(max_length=200)),
                ('postr_url', models.CharField(max_length=200, null=True)),
                ('rating_aud', models.CharField(max_length=10)),
                ('rating_cri', models.CharField(max_length=10)),
                ('rating_net', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=100)),
                ('showtimes', models.CharField(max_length=10)),
                ('release_date', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('staff', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movie.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
