# Generated by Django 3.2.5 on 2021-07-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating_rut',
            field=models.FloatField(default=0),
        ),
    ]
